app_name: petclinic

app_user: petclinic

app_group: petclinic

app_home: /opt/petclinic

service_name: petclinic

app_port: 8080

java_package: openjdk-17-jdk

jar_name: spring-petclinic.jar