---
- name: Install required packages for grafana
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana.key

- name: Convert GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/grafana.gpg /tmp/grafana.key
  args:
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    filename: grafana
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true

- name: Enable and start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started